services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:1.24.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santo_Domingo
    volumes:
      - ./volumes/freshrss:/config
    ports:
      - 8000:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
  
  cloudflared:
    image: cloudflare/cloudflared:2024.6.1
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
