services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:1.24.1
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ./volumes/freshrss:/config
    ports:
      - 8000:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M

  vaultwarden:
    image: vaultwarden/server:1.31.0
    environment:
      - INVITATIONS_ALLOWED=true
      - PGID=${PGID}
      - PUID=${PUID}
      - SIGNUPS_ALLOWED=false # Activate this with "true", create an account and then set it back to "false"
      - TZ=${TZ}
      - WEBSOCKET_ENABLED=true
    volumes:
      - ./volumes/vaultwarden:/data
    ports:
      - "8100:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M

  budge:
    image: lscr.io/linuxserver/budge:0.0.9
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ./volumes/budge:/config
    ports:
      - 8200:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 256M
        reservations:
          cpus: 0.5
          memory: 128M

  cloudflared:
    image: cloudflare/cloudflared:2024.6.1
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M

  backups:
    build:
      context: .
      dockerfile: backups.dockerfile
      args:
        - MEGA_SESSION=${MEGA_SESSION}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ./backups:/backups
      - ./volumes:/volumes
      - ./backups-encryption.key:/backups-encryption.key
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
